name: sparse
channels:
  - defaults
  - pytorch
  - conda-forge
  - nvidia
dependencies:
  - cudatoolkit=11.3
  - pytorch=1.12.1
  - torchaudio=0.12.1
  - torchvision=0.13.1
  - numpy
  - matplotlib
  - pip

