#!/bin/bash
#SBATCH -A <account name>
#SBATCH -p <partition name>
#SBATCH --mem-per-gpu=8G
#SBATCH -N 1
#SBATCH --cpus-per-gpu=9
#SBATCH --gres=gpu:8
#SBATCH --time 2880
export IMAGENET_PYTORCH=~/ImageNet # set the path to the ImageNet here.
python multiproc.py --nnodes 1 --nproc_per_node 8 imagenet_main.py --epochs 90 --opt_order after --master_port $1 --seed $2 --batch-size 32 --density 0.2 --update_frequency 800 --distributed true --use_wandb true --sparse true --fix true  --growth gradient  --workers 8 --tag "ImageNet_8GPU_u800_b32_static" --save_dir "save_b32/static/$2/" --label-smoothing 0.1 --warmup 5







